import { serve } from "https://deno.land/std@0.168.0/http/server.ts";

const RESEND_API_KEY = Deno.env.get("RESEND_API_KEY")!;

serve(async (req) => {
  if (req.method === 'OPTIONS') {
    return new Response(null, {
      headers: {
        'Access-Control-Allow-Origin': '*',
        'Access-Control-Allow-Methods': 'POST',
      },
    });
  }

  try {
    const { email, meeting_title, summary, action_items, recording_url } = await req.json();

    const actionItemsHtml = Array.isArray(action_items)
      ? action_items.map((item: any) => `<li>${item}</li>`).join('')
      : '<li>None identified</li>';

    const emailHtml = `
<!DOCTYPE html>
<html>
  <head>
    <style>
      body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', 'Roboto', 'Oxygen', 'Ubuntu', 'Cantarell', sans-serif; color: #333; }
      .container { max-width: 600px; margin: 0 auto; padding: 20px; }
      .header { background: linear-gradient(135deg, #F97316, #F59E0B); color: white; padding: 20px; border-radius: 8px; margin-bottom: 20px; }
      .section { margin-bottom: 20px; }
      .section h2 { color: #F97316; font-size: 16px; margin-bottom: 10px; }
      ul { margin: 10px 0; padding-left: 20px; }
      li { margin: 8px 0; }
      .footer { color: #999; font-size: 12px; margin-top: 30px; border-top: 1px solid #eee; padding-top: 20px; }
      .button { display: inline-block; background: #F97316; color: white; padding: 10px 20px; border-radius: 4px; text-decoration: none; margin-top: 10px; }
    </style>
  </head>
  <body>
    <div class="container">
      <div class="header">
        <h1 style="margin: 0;">Meeting Summary: ${meeting_title}</h1>
      </div>

      <div class="section">
        <h2>Summary</h2>
        <p>${summary}</p>
      </div>

      <div class="section">
        <h2>Action Items</h2>
        <ul>${actionItemsHtml}</ul>
      </div>

      ${recording_url ? `
      <div class="section">
        <a href="${recording_url}" class="button">View Recording</a>
      </div>
      ` : ''}

      <div class="footer">
        <p>This summary was generated by EchoBrief AI Meeting Intelligence.</p>
      </div>
    </div>
  </body>
</html>
    `;

    const response = await fetch('https://api.resend.com/emails', {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${RESEND_API_KEY}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        from: 'noreply@echobrief.in',
        to: email,
        subject: `Meeting Summary: ${meeting_title}`,
        html: emailHtml,
      }),
    });

    if (!response.ok) {
      throw new Error('Resend API error');
    }

    return new Response(JSON.stringify({ success: true }), {
      headers: { 'Content-Type': 'application/json' },
    });
  } catch (error) {
    console.error("Email error:", error);
    return new Response(JSON.stringify({ error: error.message }), { status: 500 });
  }
});
